---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nodejs-servicemesh
  name: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: pedroarapua/nodejs-servicemesh:latest
        command: ['npm', 'run', 'start-microservice']
        env:
        - name: GRPC_PORT
          value: "50051"
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 0.5Gi        
---
apiVersion: v1
kind: Service
metadata:
  namespace: nodejs-servicemesh
  name: microservice
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: microservice
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: nodejs-servicemesh
  name: microservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
