---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nodejs-servicemesh
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        linkerd.io/inject: ingress
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: pedroarapua/nodejs-servicemesh:latest
        command: ['npm', 'run', 'start-gateway']
        env:
        - name: NODEJS_SERVICEMESH_MICROSERVICE
          value: "http://microservice.nodejs-servicemesh.svc.cluster.local"
        - name: NODEJS_SERVICEMESH_MICROSERVICE_GRPC
          value: "microservice.nodejs-servicemesh.svc.cluster.local:50051"
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 0.5Gi        
---
apiVersion: v1
kind: Service
metadata:
  namespace: nodejs-servicemesh
  name: gateway
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gateway
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: nodejs-servicemesh
  name: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
