apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: inject-fault-split
  namespace: nodejs-servicemesh
spec:
  service: microservice
  backends:
  - service: microservice
    weight: 1000m
  - service: faulty-backend
    weight: 0m