apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: microservice.nodejs-servicemesh.svc.cluster.local
  namespace: nodejs-servicemesh
spec:
  routes:
  - name: GET /
    isRetryable: true # Define it's safe to retry this route
    timeout: 100ms # Define a timeout for this route
    condition:
      method: GET
      pathRegex: /
  - name: GET /about
    isRetryable: true # Define it's safe to retry this route
    timeout: 100ms # Define a timeout for this route
    condition:
      method: GET
      pathRegex: /about
  - name: GET /contact
    isRetryable: true # Define it's safe to retry this route
    timeout: 100ms # Define a timeout for this route
    condition:
      method: GET
      pathRegex: /contact