---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nodejs-servicemesh
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: pedroarapua/nodejs-servicemesh:latest
        command: ['npm', 'run', 'start-worker']
        env:
        - name: NODEJS_SERVICEMESH_GATEWAY_URL
          value: "http://gateway.nodejs-servicemesh.svc.cluster.local"
        - name: NODEJS_SERVICEMESH_GATEWAY_ROUTES
          value: "/timeout/error,/about"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 0.5Gi
